app = "samurai-ai"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "requests"
    soft_limit = 100
    hard_limit = 200
  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    method = "get"
    path = "/api/health"
